### ISSUE TITLE
Excelente

### ISSUE THREAD

**Issue by valeriocosta** [MicrosoftDocs/powerapps-docs.pt-br#1]
Excelente material. O aprendizado foi bem fácil e vai agregando conhecimento aos poucos.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: af7b0614-b882-02b0-7ffc-9f49e5192afe
* Version Independent ID: 8af5bc41-2f98-9d05-df22-126a6764bf93
* Content: [Gerenciando aplicativos - PowerApps](https://docs.microsoft.com/pt-br/powerapps/guided-learning/manage-apps?tutorial-step=4)
* Content Source: [powerapps-docs/guided-learning/manage-apps.yml](https://github.com/MicrosoftDocs/powerapps-docs-pr.pt-BR/blob/live-sxs/powerapps-docs/guided-learning/manage-apps.yml)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by LisandroSu** [comment]
Olá, @valeriocosta  

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
