### ISSUE TITLE
500

### ISSUE THREAD

**Issue by kiingsway** [MicrosoftDocs/powerapps-docs.pt-br#2]
t's a shame that this only counts 500 values

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5ba03a60-32b8-89a7-e0fd-ea66e3375e16
* Version Independent ID: 0b91dbe0-d729-4bed-3e55-37705cfb12b1
* Content: [Funções Count, CountA, CountIf e CountRows - PowerApps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/functions/function-table-counts)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-table-counts.md](https://github.com/MicrosoftDocs/powerapps-docs.pt-br/blob/live/powerapps-docs/maker/canvas-apps/functions/function-table-counts.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by LisandroSu** [comment]
Olá, @kiingsway , 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Enviar Comentários do Produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
