### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by AndreaOliveira** [MicrosoftDocs/powerapps-docs.pt-br#4]
Can someone help me solve this error? (401)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e58cccc6-9234-ec33-b4b0-3303ebe282ef
* Version Independent ID: a556f95f-240d-206b-6dd0-c2fc47b1bf11
* Content: [Usar Serviços Cognitivos no PowerApps - PowerApps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/cognitive-services-api)
* Content Source: [powerapps-docs/maker/canvas-apps/cognitive-services-api.md](https://github.com/MicrosoftDocs/powerapps-docs.pt-br/blob/live/powerapps-docs/maker/canvas-apps/cognitive-services-api.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by CeciAc** [comment]
Hello, @AndreaOliveira ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
