### ISSUE TITLE
Problema em Update de DataCardKey1

### ISSUE THREAD

**Issue by mariaeduardabastos** [MicrosoftDocs/powerapps-docs.pt-br#5]
Olá,
Ao mudar o controle para Allowed Value e digitar em items Distinct(Locations; Location), aparece um erro em Update de DataCardKey1. ddLocation.Selected.Value não é compatível com o resultado de Distinct. O que faço para resolver?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 234f0d1d-814d-f901-b165-211bed69242e
* Version Independent ID: bfc7f9ce-90d5-5367-85fb-463c564a3db9
* Content: [Criar uma lista suspensa dependente em um aplicativo de tela - PowerApps](https://docs.microsoft.com/pt-br/powerapps/maker/canvas-apps/dependent-drop-down-lists#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md](https://github.com/MicrosoftDocs/powerapps-docs.pt-br/blob/live/powerapps-docs/maker/canvas-apps/dependent-drop-down-lists.md)
* Service: **powerapps**
* GitHub Login: @emcoope-msft
* Microsoft Alias: **emcoope**

**Comment by srvbpigh** [comment]
Hello, @mariaeduardabastos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
