### ISSUE TITLE
Power apps  - Lookup

### ISSUE THREAD

**Issue by 12101975** [MicrosoftDocs/powerapps-docs.pt-br#6]
When I have 2 columns and I have to return value between 2 columns. Ex: column A( number 1) column B( number 10) column C ( House). I put 7 e return House. What is estructure a need to use?

**Comment by srvbpigh** [comment]
Hello, @12101975
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @12101975 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
